package actividad_1_1_d.Interfaces;

import java.io.File;
import javax.swing.JFileChooser;

public class PantallaPrincipal extends javax.swing.JFrame {

    File ficheroCargado;
    private String path;
   
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
    public PantallaPrincipal(File fichero) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ficheroCargado = fichero;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantallaPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoJMenu = new javax.swing.JMenu();
        crearFicheroJMenuItem = new javax.swing.JMenuItem();
        cargarFicheroJMenuItem = new javax.swing.JMenuItem();
        operacionesArchivoJMenu = new javax.swing.JMenu();
        contarVopcalesJMenuItem = new javax.swing.JMenuItem();
        contarPalabrasJMenuItem = new javax.swing.JMenuItem();
        salirJMenuItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad_1_1_D");
        setResizable(false);

        panelPantallaPrincipal.setMaximumSize(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("OPERACIÓN CON FICHEROS");

        javax.swing.GroupLayout panelPantallaPrincipalLayout = new javax.swing.GroupLayout(panelPantallaPrincipal);
        panelPantallaPrincipal.setLayout(panelPantallaPrincipalLayout);
        panelPantallaPrincipalLayout.setHorizontalGroup(
            panelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPantallaPrincipalLayout.setVerticalGroup(
            panelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantallaPrincipalLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        archivoJMenu.setText("Archivo");

        crearFicheroJMenuItem.setText("Crear fichero");
        crearFicheroJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFicheroJMenuItemActionPerformed(evt);
            }
        });
        archivoJMenu.add(crearFicheroJMenuItem);

        cargarFicheroJMenuItem.setText("Cargar Fichero");
        cargarFicheroJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFicheroJMenuItemActionPerformed(evt);
            }
        });
        archivoJMenu.add(cargarFicheroJMenuItem);

        jMenuBar1.add(archivoJMenu);

        operacionesArchivoJMenu.setText("Operaciones Archivo");

        contarVopcalesJMenuItem.setText("Contar vocales");
        contarVopcalesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contarVopcalesJMenuItemActionPerformed(evt);
            }
        });
        operacionesArchivoJMenu.add(contarVopcalesJMenuItem);

        contarPalabrasJMenuItem.setText("Contar palabras");
        contarPalabrasJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contarPalabrasJMenuItemActionPerformed(evt);
            }
        });
        operacionesArchivoJMenu.add(contarPalabrasJMenuItem);

        jMenuBar1.add(operacionesArchivoJMenu);

        salirJMenuItem.setText("Salir");
        salirJMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirJMenuItemMouseClicked(evt);
            }
        });
        jMenuBar1.add(salirJMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearFicheroJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFicheroJMenuItemActionPerformed

        IntroducirTexto nuevoIntroducirTexto = new IntroducirTexto();
        nuevoIntroducirTexto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearFicheroJMenuItemActionPerformed

    private void salirJMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirJMenuItemMouseClicked
        this.dispose();
    }//GEN-LAST:event_salirJMenuItemMouseClicked

    private void cargarFicheroJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFicheroJMenuItemActionPerformed

        JFileChooser nuevoJFileChooser = new JFileChooser();
        String path = "";
        File fichero = null;
                
        int valor = nuevoJFileChooser.showOpenDialog(null);

        if (valor == JFileChooser.APPROVE_OPTION) {
            
            fichero = nuevoJFileChooser.getSelectedFile();
            path = fichero.getAbsolutePath();
            
        }
        ficheroCargado = fichero;
        this.path = path; 
    }//GEN-LAST:event_cargarFicheroJMenuItemActionPerformed

    private void contarVopcalesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contarVopcalesJMenuItemActionPerformed
        
        ContarVocales nuevoContarVocales = new ContarVocales(ficheroCargado);
        nuevoContarVocales.setVisible(true);
        
    }//GEN-LAST:event_contarVopcalesJMenuItemActionPerformed

    private void contarPalabrasJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contarPalabrasJMenuItemActionPerformed
        
        ContarPalabras nuevoContarPalabras = new ContarPalabras(ficheroCargado);
        nuevoContarPalabras.setVisible(true);
        
    }//GEN-LAST:event_contarPalabrasJMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoJMenu;
    private javax.swing.JMenuItem cargarFicheroJMenuItem;
    private javax.swing.JMenuItem contarPalabrasJMenuItem;
    private javax.swing.JMenuItem contarVopcalesJMenuItem;
    private javax.swing.JMenuItem crearFicheroJMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu operacionesArchivoJMenu;
    private javax.swing.JPanel panelPantallaPrincipal;
    private javax.swing.JMenu salirJMenuItem;
    // End of variables declaration//GEN-END:variables
}
